/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AddLedgerEntryExternalIdRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public AddLedgerEntryExternalIdRequestBody requestBody;

    public AddLedgerEntryExternalIdRequest withRequestBody(AddLedgerEntryExternalIdRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=external_customer_id")
    public String externalCustomerId;

    public AddLedgerEntryExternalIdRequest withExternalCustomerId(String externalCustomerId) {
        this.externalCustomerId = externalCustomerId;
        return this;
    }
    
    public AddLedgerEntryExternalIdRequest(@JsonProperty("external_customer_id") String externalCustomerId) {
        this.externalCustomerId = externalCustomerId;
  }
}
