/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;

public class AddLedgerEntryExternalIdRequestBody {
    /**
     * The number of credits to effect. Note that this is required for increment or decrement operations.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amount")
    public Double amount;

    public AddLedgerEntryExternalIdRequestBody withAmount(Double amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * The ID of the block affected by an `expiration_change`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("block_id")
    public String blockId;

    public AddLedgerEntryExternalIdRequestBody withBlockId(String blockId) {
        this.blockId = blockId;
        return this;
    }
    
    /**
     * Optional metadata that can be specified when adding ledger results via the API. For example, this can be used to note an increment refers to trial credits, or for noting corrections as a result of an incident, etc.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("description")
    public String description;

    public AddLedgerEntryExternalIdRequestBody withDescription(String description) {
        this.description = description;
        return this;
    }
    
    @JsonProperty("entry_type")
    public AddLedgerEntryExternalIdRequestBodyEntryType entryType;

    public AddLedgerEntryExternalIdRequestBody withEntryType(AddLedgerEntryExternalIdRequestBodyEntryType entryType) {
        this.entryType = entryType;
        return this;
    }
    
    /**
     * A future date (specified in YYYY-MM-DD format) that denotes when this credit balance should expire.
     * 
     * 
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("expiry_date")
    public LocalDate expiryDate;

    public AddLedgerEntryExternalIdRequestBody withExpiryDate(LocalDate expiryDate) {
        this.expiryDate = expiryDate;
        return this;
    }
    
    /**
     * Passing `invoice_settings` automatically generates an invoice for the newly added credits. If `invoice_settings` is passed, you must specify `per_unit_cost_basis`, as the calculation of the invoice total is done on that basis.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("invoice_settings")
    public AddLedgerEntryExternalIdRequestBodyInvoiceSettings invoiceSettings;

    public AddLedgerEntryExternalIdRequestBody withInvoiceSettings(AddLedgerEntryExternalIdRequestBodyInvoiceSettings invoiceSettings) {
        this.invoiceSettings = invoiceSettings;
        return this;
    }
    
    /**
     * User-specified key/value pairs for the ledger entry resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    public AddLedgerEntryExternalIdRequestBodyMetadata metadata;

    public AddLedgerEntryExternalIdRequestBody withMetadata(AddLedgerEntryExternalIdRequestBodyMetadata metadata) {
        this.metadata = metadata;
        return this;
    }
    
    /**
     * Can only be specified when `entry_type=increment`. How much, in USD, a customer paid for a single credit in this block
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("per_unit_cost_basis")
    public String perUnitCostBasis;

    public AddLedgerEntryExternalIdRequestBody withPerUnitCostBasis(String perUnitCostBasis) {
        this.perUnitCostBasis = perUnitCostBasis;
        return this;
    }
    
    /**
     * A future date (specified in YYYY-MM-DD) used for `expiration_change`
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("target_expiry_date")
    public LocalDate targetExpiryDate;

    public AddLedgerEntryExternalIdRequestBody withTargetExpiryDate(LocalDate targetExpiryDate) {
        this.targetExpiryDate = targetExpiryDate;
        return this;
    }
    
    public AddLedgerEntryExternalIdRequestBody(@JsonProperty("entry_type") AddLedgerEntryExternalIdRequestBodyEntryType entryType) {
        this.entryType = entryType;
  }
}
