/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class AmendEventResponse {
    
    public String contentType;

    public AmendEventResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public AmendEventResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public AmendEventResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public AmendEvent200ApplicationJSON amendEvent200ApplicationJSONObject;

    public AmendEventResponse withAmendEvent200ApplicationJSONObject(AmendEvent200ApplicationJSON amendEvent200ApplicationJSONObject) {
        this.amendEvent200ApplicationJSONObject = amendEvent200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public AmendEvent400ApplicationJSON amendEvent400ApplicationJSONObject;

    public AmendEventResponse withAmendEvent400ApplicationJSONObject(AmendEvent400ApplicationJSON amendEvent400ApplicationJSONObject) {
        this.amendEvent400ApplicationJSONObject = amendEvent400ApplicationJSONObject;
        return this;
    }
    
    public AmendEventResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
