/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class AmendUsageExternalCustomerId400ApplicationJSONValidationErrors {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("idempotency_key")
    public String idempotencyKey;

    public AmendUsageExternalCustomerId400ApplicationJSONValidationErrors withIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }
    
    /**
     * An array of strings corresponding to each validation failure
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validation_errors")
    public String[] validationErrors;

    public AmendUsageExternalCustomerId400ApplicationJSONValidationErrors withValidationErrors(String[] validationErrors) {
        this.validationErrors = validationErrors;
        return this;
    }
    
    public AmendUsageExternalCustomerId400ApplicationJSONValidationErrors(){}
}
