/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;



/**
 * AmendUsageRequestBodyEventsProperties - A dictionary of custom properties. Values in this dictionary must be numeric, boolean, or strings. Nested dictionaries are disallowed.
 */
public class AmendUsageRequestBodyEventsProperties {
    public AmendUsageRequestBodyEventsProperties(){}
}
