/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;



public class AmendUsageExternalCustomerId200ApplicationJSONDuplicate {
    public AmendUsageExternalCustomerId200ApplicationJSONDuplicate(){}
}
