/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class AmendUsageExternalCustomerIdResponse {
    
    public String contentType;

    public AmendUsageExternalCustomerIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public AmendUsageExternalCustomerIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public AmendUsageExternalCustomerIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public AmendUsageExternalCustomerId200ApplicationJSON amendUsageExternalCustomerId200ApplicationJSONObject;

    public AmendUsageExternalCustomerIdResponse withAmendUsageExternalCustomerId200ApplicationJSONObject(AmendUsageExternalCustomerId200ApplicationJSON amendUsageExternalCustomerId200ApplicationJSONObject) {
        this.amendUsageExternalCustomerId200ApplicationJSONObject = amendUsageExternalCustomerId200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public AmendUsageExternalCustomerId400ApplicationJSON amendUsageExternalCustomerId400ApplicationJSONObject;

    public AmendUsageExternalCustomerIdResponse withAmendUsageExternalCustomerId400ApplicationJSONObject(AmendUsageExternalCustomerId400ApplicationJSON amendUsageExternalCustomerId400ApplicationJSONObject) {
        this.amendUsageExternalCustomerId400ApplicationJSONObject = amendUsageExternalCustomerId400ApplicationJSONObject;
        return this;
    }
    
    public AmendUsageExternalCustomerIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
