/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * AmendEvent400ApplicationJSON - Bad Request
 */
public class AmendEvent400ApplicationJSON {
    /**
     * HTTP Code
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    public Long status;

    public AmendEvent400ApplicationJSON withStatus(Long status) {
        this.status = status;
        return this;
    }
    
    /**
     * Error message
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("title")
    public String title;

    public AmendEvent400ApplicationJSON withTitle(String title) {
        this.title = title;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public String type;

    public AmendEvent400ApplicationJSON withType(String type) {
        this.type = type;
        return this;
    }
    
    /**
     * An array of strings corresponding to the validation failures
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validation_errors")
    public String[] validationErrors;

    public AmendEvent400ApplicationJSON withValidationErrors(String[] validationErrors) {
        this.validationErrors = validationErrors;
        return this;
    }
    
    public AmendEvent400ApplicationJSON(){}
}
