/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CancelSubscriptionRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public CancelSubscriptionRequestBody requestBody;

    public CancelSubscriptionRequest withRequestBody(CancelSubscriptionRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=subscription_id")
    public String subscriptionId;

    public CancelSubscriptionRequest withSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
        return this;
    }
    
    public CancelSubscriptionRequest(@JsonProperty("subscription_id") String subscriptionId) {
        this.subscriptionId = subscriptionId;
  }
}
