/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CancelSubscriptionRequestBodyCancelOption - Determines the timing of subscription cancellation
 */
public enum CancelSubscriptionRequestBodyCancelOption {
    IMMEDIATE("immediate"),
    END_OF_SUBSCRIPTION_TERM("end_of_subscription_term"),
    REQUESTED_DATE("requested_date");

    @JsonValue
    public final String value;

    private CancelSubscriptionRequestBodyCancelOption(String value) {
        this.value = value;
    }
}
