/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;



public class CreateSubscriptionApplicationXML {
    public CreateSubscriptionApplicationXML(){}
}
