/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateSubscriptionApplicationJSONPriceOverrides6BulkBpsConfig {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tiers")
    public CreateSubscriptionApplicationJSONPriceOverrides6BulkBpsConfigTiers[] tiers;

    public CreateSubscriptionApplicationJSONPriceOverrides6BulkBpsConfig withTiers(CreateSubscriptionApplicationJSONPriceOverrides6BulkBpsConfigTiers[] tiers) {
        this.tiers = tiers;
        return this;
    }
    
    public CreateSubscriptionApplicationJSONPriceOverrides6BulkBpsConfig(){}
}
