/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreateSubscriptionApplicationJSONPriceOverrides1 - Tiered price override
 */
public class CreateSubscriptionApplicationJSONPriceOverrides1 {
    /**
     * The subscription's override discount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("discount")
    public Orb.Orb.models.shared.CreateDiscount discount;

    public CreateSubscriptionApplicationJSONPriceOverrides1 withDiscount(Orb.Orb.models.shared.CreateDiscount discount) {
        this.discount = discount;
        return this;
    }
    
    /**
     * price_id
     */
    @JsonProperty("id")
    public String id;

    public CreateSubscriptionApplicationJSONPriceOverrides1 withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The subscription's override minimum amount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimum_amount")
    public String minimumAmount;

    public CreateSubscriptionApplicationJSONPriceOverrides1 withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("model_type")
    public CreateSubscriptionApplicationJSONPriceOverrides1ModelType modelType;

    public CreateSubscriptionApplicationJSONPriceOverrides1 withModelType(CreateSubscriptionApplicationJSONPriceOverrides1ModelType modelType) {
        this.modelType = modelType;
        return this;
    }
    
    @JsonProperty("tiered_config")
    public CreateSubscriptionApplicationJSONPriceOverrides1TieredConfig tieredConfig;

    public CreateSubscriptionApplicationJSONPriceOverrides1 withTieredConfig(CreateSubscriptionApplicationJSONPriceOverrides1TieredConfig tieredConfig) {
        this.tieredConfig = tieredConfig;
        return this;
    }
    
    public CreateSubscriptionApplicationJSONPriceOverrides1(@JsonProperty("id") String id, @JsonProperty("model_type") CreateSubscriptionApplicationJSONPriceOverrides1ModelType modelType, @JsonProperty("tiered_config") CreateSubscriptionApplicationJSONPriceOverrides1TieredConfig tieredConfig) {
        this.id = id;
        this.modelType = modelType;
        this.tieredConfig = tieredConfig;
  }
}
