/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class CreateSubscriptionApplicationJSONPriceOverrides1TieredConfig {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tiers")
    public CreateSubscriptionApplicationJSONPriceOverrides1TieredConfigTiers[] tiers;

    public CreateSubscriptionApplicationJSONPriceOverrides1TieredConfig withTiers(CreateSubscriptionApplicationJSONPriceOverrides1TieredConfigTiers[] tiers) {
        this.tiers = tiers;
        return this;
    }
    
    public CreateSubscriptionApplicationJSONPriceOverrides1TieredConfig(){}
}
