/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;



/**
 * CreateSubscriptionApplicationJSONMetadata - User-specified key value pairs, often useful for referencing internal resources or IDs. Returned as-is in the subscription resource.
 */
public class CreateSubscriptionApplicationJSONMetadata {
    public CreateSubscriptionApplicationJSONMetadata(){}
}
