/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateSubscriptionApplicationJSONExternalMarketplace - Optionally provide the name of the external marketplace that the subscription is attached to.
 */
public enum CreateSubscriptionApplicationJSONExternalMarketplace {
    GOOGLE("google"),
    AWS("aws"),
    AZURE("azure");

    @JsonValue
    public final String value;

    private CreateSubscriptionApplicationJSONExternalMarketplace(String value) {
        this.value = value;
    }
}
