/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;

public class CreateInvoiceLineItemRequestBody {
    /**
     * The total amount in the invoice's currency to add to the line item.
     */
    @JsonProperty("amount")
    public String amount;

    public CreateInvoiceLineItemRequestBody withAmount(String amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * An date string to specify the line item's end date in the customer's timezone.
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("end_date")
    public LocalDate endDate;

    public CreateInvoiceLineItemRequestBody withEndDate(LocalDate endDate) {
        this.endDate = endDate;
        return this;
    }
    
    /**
     * The id of the `Invoice` to add this line item.
     */
    @JsonProperty("invoice_id")
    public String invoiceId;

    public CreateInvoiceLineItemRequestBody withInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
        return this;
    }
    
    /**
     * The item name associated with this line item. If an item with the same name exists in Orb, that item will be associated with the line item.
     */
    @JsonProperty("name")
    public String name;

    public CreateInvoiceLineItemRequestBody withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * The number of units on the line item
     */
    @JsonProperty("quantity")
    public Double quantity;

    public CreateInvoiceLineItemRequestBody withQuantity(Double quantity) {
        this.quantity = quantity;
        return this;
    }
    
    /**
     * An date string to specify the line item's start date in the customer's timezone.
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @JsonProperty("start_date")
    public LocalDate startDate;

    public CreateInvoiceLineItemRequestBody withStartDate(LocalDate startDate) {
        this.startDate = startDate;
        return this;
    }
    
    public CreateInvoiceLineItemRequestBody(@JsonProperty("amount") String amount, @JsonProperty("end_date") LocalDate endDate, @JsonProperty("invoice_id") String invoiceId, @JsonProperty("name") String name, @JsonProperty("quantity") Double quantity, @JsonProperty("start_date") LocalDate startDate) {
        this.amount = amount;
        this.endDate = endDate;
        this.invoiceId = invoiceId;
        this.name = name;
        this.quantity = quantity;
        this.startDate = startDate;
  }
}
