/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateCustomerRequestBodyPaymentProvider - This is used for creating charges or invoices in an external system via Orb. When not in test mode:
 * - the connection must first be configured in the Orb webapp. 
 * - if the provider is an invoicing provider (`stripe_invoice`, `quickbooks`, `bill.com`), any product mappings must first be configured with the Orb team.
 */
public enum CreateCustomerRequestBodyPaymentProvider {
    QUICKBOOKS("quickbooks"),
    BILL_COM("bill.com"),
    STRIPE_CHARGE("stripe_charge"),
    STRIPE_INVOICE("stripe_invoice"),
    NULL_("null");

    @JsonValue
    public final String value;

    private CreateCustomerRequestBodyPaymentProvider(String value) {
        this.value = value;
    }
}
