/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

public enum CreateLedgerEntryRequestBodyEntryType {
    INCREMENT("increment"),
    DECREMENT("decrement"),
    EXPIRATION_CHANGE("expiration_change");

    @JsonValue
    public final String value;

    private CreateLedgerEntryRequestBodyEntryType(String value) {
        this.value = value;
    }
}
