/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class DeprecateEventResponse {
    
    public String contentType;

    public DeprecateEventResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public DeprecateEventResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeprecateEventResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public DeprecateEvent200ApplicationJSON deprecateEvent200ApplicationJSONObject;

    public DeprecateEventResponse withDeprecateEvent200ApplicationJSONObject(DeprecateEvent200ApplicationJSON deprecateEvent200ApplicationJSONObject) {
        this.deprecateEvent200ApplicationJSONObject = deprecateEvent200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public DeprecateEvent400ApplicationJSON deprecateEvent400ApplicationJSONObject;

    public DeprecateEventResponse withDeprecateEvent400ApplicationJSONObject(DeprecateEvent400ApplicationJSON deprecateEvent400ApplicationJSONObject) {
        this.deprecateEvent400ApplicationJSONObject = deprecateEvent400ApplicationJSONObject;
        return this;
    }
    
    public DeprecateEventResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
