/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FetchSubscriptionSchedule200ApplicationJSON - OK
 */
public class FetchSubscriptionSchedule200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public FetchSubscriptionSchedule200ApplicationJSONData[] data;

    public FetchSubscriptionSchedule200ApplicationJSON withData(FetchSubscriptionSchedule200ApplicationJSONData[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pagination_metadata")
    public Orb.Orb.models.shared.PaginationMetadata paginationMetadata;

    public FetchSubscriptionSchedule200ApplicationJSON withPaginationMetadata(Orb.Orb.models.shared.PaginationMetadata paginationMetadata) {
        this.paginationMetadata = paginationMetadata;
        return this;
    }
    
    public FetchSubscriptionSchedule200ApplicationJSON(){}
}
