/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FetchCustomerCreditsExternalId200ApplicationJSON - OK
 */
public class FetchCustomerCreditsExternalId200ApplicationJSON {
    @JsonProperty("data")
    public FetchCustomerCreditsExternalId200ApplicationJSONData[] data;

    public FetchCustomerCreditsExternalId200ApplicationJSON withData(FetchCustomerCreditsExternalId200ApplicationJSONData[] data) {
        this.data = data;
        return this;
    }
    
    @JsonProperty("pagination_metadata")
    public FetchCustomerCreditsExternalId200ApplicationJSONPaginationMetadata paginationMetadata;

    public FetchCustomerCreditsExternalId200ApplicationJSON withPaginationMetadata(FetchCustomerCreditsExternalId200ApplicationJSONPaginationMetadata paginationMetadata) {
        this.paginationMetadata = paginationMetadata;
        return this;
    }
    
    public FetchCustomerCreditsExternalId200ApplicationJSON(@JsonProperty("data") FetchCustomerCreditsExternalId200ApplicationJSONData[] data, @JsonProperty("pagination_metadata") FetchCustomerCreditsExternalId200ApplicationJSONPaginationMetadata paginationMetadata) {
        this.data = data;
        this.paginationMetadata = paginationMetadata;
  }
}
