/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.DateTimeDeserializer;
import Orb.Orb.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class FetchSubscriptionSchedule200ApplicationJSONData {
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("end_date")
    public OffsetDateTime endDate;

    public FetchSubscriptionSchedule200ApplicationJSONData withEndDate(OffsetDateTime endDate) {
        this.endDate = endDate;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("plan")
    public FetchSubscriptionSchedule200ApplicationJSONDataPlan plan;

    public FetchSubscriptionSchedule200ApplicationJSONData withPlan(FetchSubscriptionSchedule200ApplicationJSONDataPlan plan) {
        this.plan = plan;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("start_date")
    public OffsetDateTime startDate;

    public FetchSubscriptionSchedule200ApplicationJSONData withStartDate(OffsetDateTime startDate) {
        this.startDate = startDate;
        return this;
    }
    
    public FetchSubscriptionSchedule200ApplicationJSONData(){}
}
