/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

public class FetchCustomerCostsRequest {
    /**
     * The Orb Customer ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=customer_id")
    public String customerId;

    public FetchCustomerCostsRequest withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }
    
    /**
     * Groups per-price costs by the key provided.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=group_by")
    public String groupBy;

    public FetchCustomerCostsRequest withGroupBy(String groupBy) {
        this.groupBy = groupBy;
        return this;
    }
    
    /**
     * Costs returned are exclusive of `timeframe_end`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=timeframe_end")
    public String timeframeEnd;

    public FetchCustomerCostsRequest withTimeframeEnd(String timeframeEnd) {
        this.timeframeEnd = timeframeEnd;
        return this;
    }
    
    /**
     * Costs returned are inclusive of `timeframe_start`.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=timeframe_start")
    public OffsetDateTime timeframeStart;

    public FetchCustomerCostsRequest withTimeframeStart(OffsetDateTime timeframeStart) {
        this.timeframeStart = timeframeStart;
        return this;
    }
    
    /**
     * Controls whether Orb returns cumulative costs since the start of the billing period, or incremental day-by-day costs. If your customer has minimums or discounts, it's strongly recommended that you use the default cumulative behavior.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=view_mode")
    public FetchCustomerCostsViewMode viewMode;

    public FetchCustomerCostsRequest withViewMode(FetchCustomerCostsViewMode viewMode) {
        this.viewMode = viewMode;
        return this;
    }
    
    public FetchCustomerCostsRequest(@JsonProperty("customer_id") String customerId) {
        this.customerId = customerId;
  }
}
