/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class FetchCustomerCostsResponse {
    
    public String contentType;

    public FetchCustomerCostsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public FetchCustomerCostsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FetchCustomerCostsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public FetchCustomerCosts200ApplicationJSON fetchCustomerCosts200ApplicationJSONObject;

    public FetchCustomerCostsResponse withFetchCustomerCosts200ApplicationJSONObject(FetchCustomerCosts200ApplicationJSON fetchCustomerCosts200ApplicationJSONObject) {
        this.fetchCustomerCosts200ApplicationJSONObject = fetchCustomerCosts200ApplicationJSONObject;
        return this;
    }
    
    public FetchCustomerCostsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
