/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FetchCustomerCosts200ApplicationJSON - OK
 */
public class FetchCustomerCosts200ApplicationJSON {
    @JsonProperty("data")
    public FetchCustomerCosts200ApplicationJSONData[] data;

    public FetchCustomerCosts200ApplicationJSON withData(FetchCustomerCosts200ApplicationJSONData[] data) {
        this.data = data;
        return this;
    }
    
    @JsonProperty("pagination_metadata")
    public Orb.Orb.models.shared.PaginationMetadata paginationMetadata;

    public FetchCustomerCosts200ApplicationJSON withPaginationMetadata(Orb.Orb.models.shared.PaginationMetadata paginationMetadata) {
        this.paginationMetadata = paginationMetadata;
        return this;
    }
    
    public FetchCustomerCosts200ApplicationJSON(@JsonProperty("data") FetchCustomerCosts200ApplicationJSONData[] data, @JsonProperty("pagination_metadata") Orb.Orb.models.shared.PaginationMetadata paginationMetadata) {
        this.data = data;
        this.paginationMetadata = paginationMetadata;
  }
}
