/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class FetchCustomerCreditsLedgerResponse {
    
    public String contentType;

    public FetchCustomerCreditsLedgerResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public FetchCustomerCreditsLedgerResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public FetchCustomerCreditsLedgerResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public FetchCustomerCreditsLedger200ApplicationJSON fetchCustomerCreditsLedger200ApplicationJSONObject;

    public FetchCustomerCreditsLedgerResponse withFetchCustomerCreditsLedger200ApplicationJSONObject(FetchCustomerCreditsLedger200ApplicationJSON fetchCustomerCreditsLedger200ApplicationJSONObject) {
        this.fetchCustomerCreditsLedger200ApplicationJSONObject = fetchCustomerCreditsLedger200ApplicationJSONObject;
        return this;
    }
    
    public FetchCustomerCreditsLedgerResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
