/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.DateTimeDeserializer;
import Orb.Orb.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class FetchCustomerCredits200ApplicationJSONData {
    /**
     * Remaining credits in this block
     */
    @JsonProperty("balance")
    public Double balance;

    public FetchCustomerCredits200ApplicationJSONData withBalance(Double balance) {
        this.balance = balance;
        return this;
    }
    
    /**
     * An ISO 8601 format date with a timezone offset that represents when this block of credits is no longer usable.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("expiry_date")
    public OffsetDateTime expiryDate;

    public FetchCustomerCredits200ApplicationJSONData withExpiryDate(OffsetDateTime expiryDate) {
        this.expiryDate = expiryDate;
        return this;
    }
    
    @JsonProperty("id")
    public String id;

    public FetchCustomerCredits200ApplicationJSONData withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * How much, in USD, a customer paid for a single credit in this block
     */
    @JsonProperty("per_unit_cost_basis")
    public String perUnitCostBasis;

    public FetchCustomerCredits200ApplicationJSONData withPerUnitCostBasis(String perUnitCostBasis) {
        this.perUnitCostBasis = perUnitCostBasis;
        return this;
    }
    
    public FetchCustomerCredits200ApplicationJSONData(@JsonProperty("balance") Double balance, @JsonProperty("expiry_date") OffsetDateTime expiryDate, @JsonProperty("id") String id, @JsonProperty("per_unit_cost_basis") String perUnitCostBasis) {
        this.balance = balance;
        this.expiryDate = expiryDate;
        this.id = id;
        this.perUnitCostBasis = perUnitCostBasis;
  }
}
