/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.DateTimeDeserializer;
import Orb.Orb.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class FetchCustomerCosts200ApplicationJSONData {
    @JsonProperty("per_price_costs")
    public FetchCustomerCosts200ApplicationJSONDataPerPriceCosts[] perPriceCosts;

    public FetchCustomerCosts200ApplicationJSONData withPerPriceCosts(FetchCustomerCosts200ApplicationJSONDataPerPriceCosts[] perPriceCosts) {
        this.perPriceCosts = perPriceCosts;
        return this;
    }
    
    /**
     * Total costs for the timeframe, excluding minimums and discounts.
     */
    @JsonProperty("subtotal")
    public String subtotal;

    public FetchCustomerCosts200ApplicationJSONData withSubtotal(String subtotal) {
        this.subtotal = subtotal;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("timeframe_end")
    public OffsetDateTime timeframeEnd;

    public FetchCustomerCosts200ApplicationJSONData withTimeframeEnd(OffsetDateTime timeframeEnd) {
        this.timeframeEnd = timeframeEnd;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("timeframe_start")
    public OffsetDateTime timeframeStart;

    public FetchCustomerCosts200ApplicationJSONData withTimeframeStart(OffsetDateTime timeframeStart) {
        this.timeframeStart = timeframeStart;
        return this;
    }
    
    /**
     * Total costs for the timeframe, including minimums and discounts.
     */
    @JsonProperty("total")
    public String total;

    public FetchCustomerCosts200ApplicationJSONData withTotal(String total) {
        this.total = total;
        return this;
    }
    
    public FetchCustomerCosts200ApplicationJSONData(@JsonProperty("per_price_costs") FetchCustomerCosts200ApplicationJSONDataPerPriceCosts[] perPriceCosts, @JsonProperty("subtotal") String subtotal, @JsonProperty("timeframe_end") OffsetDateTime timeframeEnd, @JsonProperty("timeframe_start") OffsetDateTime timeframeStart, @JsonProperty("total") String total) {
        this.perPriceCosts = perPriceCosts;
        this.subtotal = subtotal;
        this.timeframeEnd = timeframeEnd;
        this.timeframeStart = timeframeStart;
        this.total = total;
  }
}
