/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FetchSubscriptionUsageGranularity - This determines the windowing of usage reporting.
 */
public enum FetchSubscriptionUsageGranularity {
    DAY("day");

    @JsonValue
    public final String value;

    private FetchSubscriptionUsageGranularity(String value) {
        this.value = value;
    }
}
