/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class FetchCouponRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=coupon_id")
    public String couponId;

    public FetchCouponRequest withCouponId(String couponId) {
        this.couponId = couponId;
        return this;
    }
    
    public FetchCouponRequest(@JsonProperty("coupon_id") String couponId) {
        this.couponId = couponId;
  }
}
