/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FetchCustomerCostsExternalId200ApplicationJSON - OK
 */
public class FetchCustomerCostsExternalId200ApplicationJSON {
    @JsonProperty("data")
    public FetchCustomerCostsExternalId200ApplicationJSONData[] data;

    public FetchCustomerCostsExternalId200ApplicationJSON withData(FetchCustomerCostsExternalId200ApplicationJSONData[] data) {
        this.data = data;
        return this;
    }
    
    @JsonProperty("pagination_metadata")
    public Orb.Orb.models.shared.PaginationMetadata paginationMetadata;

    public FetchCustomerCostsExternalId200ApplicationJSON withPaginationMetadata(Orb.Orb.models.shared.PaginationMetadata paginationMetadata) {
        this.paginationMetadata = paginationMetadata;
        return this;
    }
    
    public FetchCustomerCostsExternalId200ApplicationJSON(@JsonProperty("data") FetchCustomerCostsExternalId200ApplicationJSONData[] data, @JsonProperty("pagination_metadata") Orb.Orb.models.shared.PaginationMetadata paginationMetadata) {
        this.data = data;
        this.paginationMetadata = paginationMetadata;
  }
}
