/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class GetCustomersCustomerIdCreditsResponse {
    
    public String contentType;

    public GetCustomersCustomerIdCreditsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public GetCustomersCustomerIdCreditsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetCustomersCustomerIdCreditsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public GetCustomersCustomerIdCredits200ApplicationJSON getCustomersCustomerIdCredits200ApplicationJSONObject;

    public GetCustomersCustomerIdCreditsResponse withGetCustomersCustomerIdCredits200ApplicationJSONObject(GetCustomersCustomerIdCredits200ApplicationJSON getCustomersCustomerIdCredits200ApplicationJSONObject) {
        this.getCustomersCustomerIdCredits200ApplicationJSONObject = getCustomersCustomerIdCredits200ApplicationJSONObject;
        return this;
    }
    
    public GetCustomersCustomerIdCreditsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
