/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * GetCustomersCustomerIdCreditsLedgerEntryStatus - Filters to a single status of ledger entry
 */
public enum GetCustomersCustomerIdCreditsLedgerEntryStatus {
    COMMITTED("committed"),
    PENDING("pending");

    @JsonValue
    public final String value;

    private GetCustomersCustomerIdCreditsLedgerEntryStatus(String value) {
        this.value = value;
    }
}
