/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetExternalCustomerCosts200ApplicationJSON - OK
 */
public class GetExternalCustomerCosts200ApplicationJSON {
    @JsonProperty("data")
    public GetExternalCustomerCosts200ApplicationJSONData[] data;
    public GetExternalCustomerCosts200ApplicationJSON withData(GetExternalCustomerCosts200ApplicationJSONData[] data) {
        this.data = data;
        return this;
    }
    
    @JsonProperty("pagination_metadata")
    public java.util.Map<String, Object> paginationMetadata;
    public GetExternalCustomerCosts200ApplicationJSON withPaginationMetadata(java.util.Map<String, Object> paginationMetadata) {
        this.paginationMetadata = paginationMetadata;
        return this;
    }
    
    public GetExternalCustomerCosts200ApplicationJSON(@JsonProperty("data") GetExternalCustomerCosts200ApplicationJSONData[] data, @JsonProperty("pagination_metadata") java.util.Map<String, Object> paginationMetadata) {
        this.data = data;
        this.paginationMetadata = paginationMetadata;
  }
}
