/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import java.net.http.HttpResponse;

public class GetInvoicesUpcomingResponse {
    
    public String contentType;
    public GetInvoicesUpcomingResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public GetInvoicesUpcomingResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public GetInvoicesUpcomingResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public Orb.Orb.models.shared.UpcomingInvoice upcomingInvoice;
    public GetInvoicesUpcomingResponse withUpcomingInvoice(Orb.Orb.models.shared.UpcomingInvoice upcomingInvoice) {
        this.upcomingInvoice = upcomingInvoice;
        return this;
    }
    
}
