/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * GetPing200ApplicationJSON - OK
 */
public class GetPing200ApplicationJSON {
    @JsonProperty("response")
    public String response;
    public GetPing200ApplicationJSON withResponse(String response) {
        this.response = response;
        return this;
    }
    
}
