/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;

public class GetPlansPlanIdRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=plan_id")
    public String planId;
    public GetPlansPlanIdRequest withPlanId(String planId) {
        this.planId = planId;
        return this;
    }
    
}
