/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GetSubscriptionsSubscriptionIdSchedule200ApplicationJSONDataPlan {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    public String id;

    public GetSubscriptionsSubscriptionIdSchedule200ApplicationJSONDataPlan withId(String id) {
        this.id = id;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public GetSubscriptionsSubscriptionIdSchedule200ApplicationJSONDataPlan withName(String name) {
        this.name = name;
        return this;
    }
    
    public GetSubscriptionsSubscriptionIdSchedule200ApplicationJSONDataPlan(){}
}
