/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;

public class IngestRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public IngestRequestBody requestBody;

    public IngestRequest withRequestBody(IngestRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * If this ingestion request is part of a backfill, this parameter ties the ingested events to the backfill
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=backfill_id")
    public String backfillId;

    public IngestRequest withBackfillId(String backfillId) {
        this.backfillId = backfillId;
        return this;
    }
    
    /**
     * Flag to enable additional debug information in the endpoint response
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=debug")
    public IngestDebug debug;

    public IngestRequest withDebug(IngestDebug debug) {
        this.debug = debug;
        return this;
    }
    
    public IngestRequest(){}
}
