/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class IngestResponse {
    
    public String contentType;

    public IngestResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public IngestResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public IngestResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public Ingest200ApplicationJSON ingest200ApplicationJSONObject;

    public IngestResponse withIngest200ApplicationJSONObject(Ingest200ApplicationJSON ingest200ApplicationJSONObject) {
        this.ingest200ApplicationJSONObject = ingest200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public Ingest400ApplicationJSON ingest400ApplicationJSONObject;

    public IngestResponse withIngest400ApplicationJSONObject(Ingest400ApplicationJSON ingest400ApplicationJSONObject) {
        this.ingest400ApplicationJSONObject = ingest400ApplicationJSONObject;
        return this;
    }
    
    public IngestResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
