/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Ingest200ApplicationJSONValidationFailed {
    /**
     * The passed idempotency_key corresponding to the validation_errors
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("idempotency_key")
    public String idempotencyKey;

    public Ingest200ApplicationJSONValidationFailed withIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }
    
    /**
     * An array of objects corresponding to validation failures for each idempotency_key.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validation_errors")
    public java.util.Map<String, Object>[] validationErrors;

    public Ingest200ApplicationJSONValidationFailed withValidationErrors(java.util.Map<String, Object>[] validationErrors) {
        this.validationErrors = validationErrors;
        return this;
    }
    
    public Ingest200ApplicationJSONValidationFailed(){}
}
