/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Ingest200ApplicationJSON - OK
 */
public class Ingest200ApplicationJSON {
    /**
     * Optional debug information (only present when debug=true is passed to the endpoint). Contains ingested and duplicate event idempotency keys.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("debug")
    public Ingest200ApplicationJSONDebug debug;

    public Ingest200ApplicationJSON withDebug(Ingest200ApplicationJSONDebug debug) {
        this.debug = debug;
        return this;
    }
    
    /**
     * Contains all failing validation events. In the case of a 200, this array will always be empty. This field will always be present.
     */
    @JsonProperty("validation_failed")
    public Ingest200ApplicationJSONValidationFailed[] validationFailed;

    public Ingest200ApplicationJSON withValidationFailed(Ingest200ApplicationJSONValidationFailed[] validationFailed) {
        this.validationFailed = validationFailed;
        return this;
    }
    
    public Ingest200ApplicationJSON(@JsonProperty("validation_failed") Ingest200ApplicationJSONValidationFailed[] validationFailed) {
        this.validationFailed = validationFailed;
  }
}
