/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListBackfillsResponse {
    
    public String contentType;

    public ListBackfillsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ListBackfillsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListBackfillsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListBackfills200ApplicationJSON listBackfills200ApplicationJSONObject;

    public ListBackfillsResponse withListBackfills200ApplicationJSONObject(ListBackfills200ApplicationJSON listBackfills200ApplicationJSONObject) {
        this.listBackfills200ApplicationJSONObject = listBackfills200ApplicationJSONObject;
        return this;
    }
    
    public ListBackfillsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
