/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class ListCouponSubscriptionsResponse {
    
    public String contentType;

    public ListCouponSubscriptionsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public ListCouponSubscriptionsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public ListCouponSubscriptionsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public ListCouponSubscriptions200ApplicationJSON listCouponSubscriptions200ApplicationJSONObject;

    public ListCouponSubscriptionsResponse withListCouponSubscriptions200ApplicationJSONObject(ListCouponSubscriptions200ApplicationJSON listCouponSubscriptions200ApplicationJSONObject) {
        this.listCouponSubscriptions200ApplicationJSONObject = listCouponSubscriptions200ApplicationJSONObject;
        return this;
    }
    
    public ListCouponSubscriptionsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
