/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListCouponSubscriptions200ApplicationJSON - OK
 */
public class ListCouponSubscriptions200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Orb.Orb.models.shared.Subscription[] data;

    public ListCouponSubscriptions200ApplicationJSON withData(Orb.Orb.models.shared.Subscription[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pagination_metadata")
    public Orb.Orb.models.shared.PaginationMetadata paginationMetadata;

    public ListCouponSubscriptions200ApplicationJSON withPaginationMetadata(Orb.Orb.models.shared.PaginationMetadata paginationMetadata) {
        this.paginationMetadata = paginationMetadata;
        return this;
    }
    
    public ListCouponSubscriptions200ApplicationJSON(){}
}
