/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;

public class ListSubscriptionsRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=customer_id")
    public String customerId;
    public ListSubscriptionsRequest withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=external_customer_id")
    public String externalCustomerId;
    public ListSubscriptionsRequest withExternalCustomerId(String externalCustomerId) {
        this.externalCustomerId = externalCustomerId;
        return this;
    }
    

    public ListSubscriptionsRequest(){}
}
