/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListCustomers200ApplicationJSON - OK
 */
public class ListCustomers200ApplicationJSON {
    @JsonProperty("data")
    public Orb.Orb.models.shared.Customer[] data;
    public ListCustomers200ApplicationJSON withData(Orb.Orb.models.shared.Customer[] data) {
        this.data = data;
        return this;
    }
    
    @JsonProperty("pagination_metadata")
    public ListCustomers200ApplicationJSONPaginationMetadata paginationMetadata;
    public ListCustomers200ApplicationJSON withPaginationMetadata(ListCustomers200ApplicationJSONPaginationMetadata paginationMetadata) {
        this.paginationMetadata = paginationMetadata;
        return this;
    }
    
}
