/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ListCoupons200ApplicationJSON - OK
 */
public class ListCoupons200ApplicationJSON {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public Orb.Orb.models.shared.Coupon[] data;

    public ListCoupons200ApplicationJSON withData(Orb.Orb.models.shared.Coupon[] data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pagination_metadata")
    public Orb.Orb.models.shared.PaginationMetadata paginationMetadata;

    public ListCoupons200ApplicationJSON withPaginationMetadata(Orb.Orb.models.shared.PaginationMetadata paginationMetadata) {
        this.paginationMetadata = paginationMetadata;
        return this;
    }
    
    public ListCoupons200ApplicationJSON(){}
}
