/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;
import java.time.OffsetDateTime;

public class PatchCustomersCustomerIdUsageRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PatchCustomersCustomerIdUsageRequestBody requestBody;
    public PatchCustomersCustomerIdUsageRequest withRequestBody(PatchCustomersCustomerIdUsageRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=customer_id")
    public String customerId;
    public PatchCustomersCustomerIdUsageRequest withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }
    
    /**
     * This bound is exclusive (i.e. events before this timestamp will be updated)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=timeframe_end")
    public OffsetDateTime timeframeEnd;
    public PatchCustomersCustomerIdUsageRequest withTimeframeEnd(OffsetDateTime timeframeEnd) {
        this.timeframeEnd = timeframeEnd;
        return this;
    }
    
    /**
     * This bound is inclusive (i.e. events with this timestamp onward, inclusive will be updated)
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=timeframe_start")
    public OffsetDateTime timeframeStart;
    public PatchCustomersCustomerIdUsageRequest withTimeframeStart(OffsetDateTime timeframeStart) {
        this.timeframeStart = timeframeStart;
        return this;
    }
    
}
