/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostIngest400ApplicationJSON - Bad Request
 */
public class PostIngest400ApplicationJSON {
    /**
     * Optional debug information (only present when debug=true is passed to the endpoint). Contains ingested and duplicate event idempotency keys.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("debug")
    public PostIngest400ApplicationJSONDebug debug;
    public PostIngest400ApplicationJSON withDebug(PostIngest400ApplicationJSONDebug debug) {
        this.debug = debug;
        return this;
    }
    
    /**
     * Contains all failing validation events. In the case of a 400, there will be at least one entry in this array.
     */
    @JsonProperty("validation_failed")
    public PostIngest400ApplicationJSONValidationFailed[] validationFailed;
    public PostIngest400ApplicationJSON withValidationFailed(PostIngest400ApplicationJSONValidationFailed[] validationFailed) {
        this.validationFailed = validationFailed;
        return this;
    }
    
}
