/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7 - Tiered BPS price override
 */
public class PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7 {
    @JsonProperty("id")
    public String id;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7 withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The subscription's override minimum amount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimum_amount")
    public String minimumAmount;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7 withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("model_type")
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum modelType;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7 withModelType(PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7ModelTypeEnum modelType) {
        this.modelType = modelType;
        return this;
    }
    
    @JsonProperty("tiered_bps_config")
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfig tieredBpsConfig;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7 withTieredBpsConfig(PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfig tieredBpsConfig) {
        this.tieredBpsConfig = tieredBpsConfig;
        return this;
    }
    
}
