/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PostSubscriptionsRequestBodyPriceOverrides5BpsConfig {
    @JsonProperty("bps")
    public Double bps;
    public PostSubscriptionsRequestBodyPriceOverrides5BpsConfig withBps(Double bps) {
        this.bps = bps;
        return this;
    }
    
    @JsonProperty("per_unit_maximum")
    public String perUnitMaximum;
    public PostSubscriptionsRequestBodyPriceOverrides5BpsConfig withPerUnitMaximum(String perUnitMaximum) {
        this.perUnitMaximum = perUnitMaximum;
        return this;
    }
    
}
