/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PostIngest400ApplicationJSONValidationFailed {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("idempotency_key")
    public String idempotencyKey;
    public PostIngest400ApplicationJSONValidationFailed withIdempotencyKey(String idempotencyKey) {
        this.idempotencyKey = idempotencyKey;
        return this;
    }
    
    /**
     * An array of objects corresponding to validation failures for each idempotency_key.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("validation_errors")
    public String[] validationErrors;
    public PostIngest400ApplicationJSONValidationFailed withValidationErrors(String[] validationErrors) {
        this.validationErrors = validationErrors;
        return this;
    }
    
    public PostIngest400ApplicationJSONValidationFailed(){}
}
