/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5 - BPS price override
 */
public class PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5 {
    @JsonProperty("bps_config")
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5BpsConfig bpsConfig;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5 withBpsConfig(PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5BpsConfig bpsConfig) {
        this.bpsConfig = bpsConfig;
        return this;
    }
    
    @JsonProperty("id")
    public String id;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5 withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The subscription's override minimum amount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimum_amount")
    public String minimumAmount;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5 withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("model_type")
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum modelType;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5 withModelType(PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum modelType) {
        this.modelType = modelType;
        return this;
    }
    

    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5(@JsonProperty("bps_config") PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5BpsConfig bpsConfig, @JsonProperty("id") String id, @JsonProperty("model_type") PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides5ModelTypeEnum modelType) {
    this.bpsConfig = bpsConfig;
this.id = id;
this.modelType = modelType;
  }
}
