/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostSubscriptionsSubscriptionIdCancelCancelOption - Determines the timing of subscription cancellation
 */
public enum PostSubscriptionsSubscriptionIdCancelCancelOption {
    END_OF_SUBSCRIPTION_TERM("end_of_subscription_term"),
    IMMEDIATE("immediate");

    @JsonValue
    public final String value;

    private PostSubscriptionsSubscriptionIdCancelCancelOption(String value) {
        this.value = value;
    }
}
