/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostIngestDebugEnum - Flag to enable additional debug information in the endpoint response
 */
public enum PostIngestDebugEnum {
    TRUE("true"),
    FALSE("false");

    @JsonValue
    public final String value;

    private PostIngestDebugEnum(String value) {
        this.value = value;
    }
}
