/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6 - Bulk BPS price override
 */
public class PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6 {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bulk_bps_config")
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6BulkBpsConfig bulkBpsConfig;

    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6 withBulkBpsConfig(PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6BulkBpsConfig bulkBpsConfig) {
        this.bulkBpsConfig = bulkBpsConfig;
        return this;
    }
    
    @JsonProperty("id")
    public String id;

    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6 withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The subscription's override minimum amount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimum_amount")
    public String minimumAmount;

    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6 withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("model_type")
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6ModelType modelType;

    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6 withModelType(PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6ModelType modelType) {
        this.modelType = modelType;
        return this;
    }
    
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6(@JsonProperty("id") String id, @JsonProperty("model_type") PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides6ModelType modelType) {
        this.id = id;
        this.modelType = modelType;
  }
}
