/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PostInvoicesInvoiceIdVoidResponse {
    
    public String contentType;

    public PostInvoicesInvoiceIdVoidResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Created
     */
    
    public Orb.Orb.models.shared.Invoice invoice;

    public PostInvoicesInvoiceIdVoidResponse withInvoice(Orb.Orb.models.shared.Invoice invoice) {
        this.invoice = invoice;
        return this;
    }
    
    
    public Integer statusCode;

    public PostInvoicesInvoiceIdVoidResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PostInvoicesInvoiceIdVoidResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PostInvoicesInvoiceIdVoidResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
