/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

public enum PostSubscriptionsRequestBodyPriceOverrides3ModelTypeEnum {
    BULK("bulk");

    @JsonValue
    public final String value;

    private PostSubscriptionsRequestBodyPriceOverrides3ModelTypeEnum(String value) {
        this.value = value;
    }
}
