/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyChangeOption - Determines the timing of the plan change
 */
public enum PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyChangeOption {
    REQUESTED_DATE("requested_date"),
    END_OF_SUBSCRIPTION_TERM("end_of_subscription_term"),
    IMMEDIATE("immediate");

    @JsonValue
    public final String value;

    private PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyChangeOption(String value) {
        this.value = value;
    }
}
