/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PostCustomersCustomerIdCreditsLedgerEntryRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PostCustomersCustomerIdCreditsLedgerEntryRequestBody requestBody;
    public PostCustomersCustomerIdCreditsLedgerEntryRequest withRequestBody(PostCustomersCustomerIdCreditsLedgerEntryRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=customer_id")
    public String customerId;
    public PostCustomersCustomerIdCreditsLedgerEntryRequest withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }
    
    public PostCustomersCustomerIdCreditsLedgerEntryRequest(@JsonProperty("customer_id") String customerId) {
        this.customerId = customerId;
  }
}
