/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostSubscriptionsRequestBodyPriceOverrides5 - BPS price override
 */
public class PostSubscriptionsRequestBodyPriceOverrides5 {
    @JsonProperty("bps_config")
    public PostSubscriptionsRequestBodyPriceOverrides5BpsConfig bpsConfig;

    public PostSubscriptionsRequestBodyPriceOverrides5 withBpsConfig(PostSubscriptionsRequestBodyPriceOverrides5BpsConfig bpsConfig) {
        this.bpsConfig = bpsConfig;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("discount")
    public java.util.Map<String, Object> discount;

    public PostSubscriptionsRequestBodyPriceOverrides5 withDiscount(java.util.Map<String, Object> discount) {
        this.discount = discount;
        return this;
    }
    
    @JsonProperty("id")
    public String id;

    public PostSubscriptionsRequestBodyPriceOverrides5 withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The subscription's override minimum amount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimum_amount")
    public String minimumAmount;

    public PostSubscriptionsRequestBodyPriceOverrides5 withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("model_type")
    public PostSubscriptionsRequestBodyPriceOverrides5ModelType modelType;

    public PostSubscriptionsRequestBodyPriceOverrides5 withModelType(PostSubscriptionsRequestBodyPriceOverrides5ModelType modelType) {
        this.modelType = modelType;
        return this;
    }
    
    public PostSubscriptionsRequestBodyPriceOverrides5(@JsonProperty("bps_config") PostSubscriptionsRequestBodyPriceOverrides5BpsConfig bpsConfig, @JsonProperty("id") String id, @JsonProperty("model_type") PostSubscriptionsRequestBodyPriceOverrides5ModelType modelType) {
        this.bpsConfig = bpsConfig;
        this.id = id;
        this.modelType = modelType;
  }
}
