/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3 - Bulk price override
 */
public class PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3 {
    @JsonProperty("bulk_config")
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3BulkConfig bulkConfig;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3 withBulkConfig(PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3BulkConfig bulkConfig) {
        this.bulkConfig = bulkConfig;
        return this;
    }
    
    @JsonProperty("id")
    public String id;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3 withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The subscription's override minimum amount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimum_amount")
    public String minimumAmount;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3 withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("model_type")
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum modelType;
    public PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3 withModelType(PostSubscriptionsSubscriptionIdSchedulePlanChangeRequestBodyPriceOverrides3ModelTypeEnum modelType) {
        this.modelType = modelType;
        return this;
    }
    
}
