/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class PostEventsSearchRequestBody {
    /**
     * This is an explicit array of IDs to filter by. Note that an event's ID is the idempotency_key that was originally used for ingestion. Values in this array will be treated case sensitively.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_ids")
    public String[] eventIds;
    public PostEventsSearchRequestBody withEventIds(String[] eventIds) {
        this.eventIds = eventIds;
        return this;
    }
    
    /**
     * This is an issued Orb invoice ID (see also List Invoices). Orb will fetch all events that were used to calculate the invoice. In the common case, this will be a list of events whose timestamp property falls within the billing period specified by the invoice.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("invoice_id")
    public String invoiceId;
    public PostEventsSearchRequestBody withInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
        return this;
    }
    
    public PostEventsSearchRequestBody(){}
}
