/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import java.net.http.HttpResponse;

public class PostSubscriptionsSubscriptionIdUnschedulePendingPlanChangesResponse {
    
    public String contentType;
    public PostSubscriptionsSubscriptionIdUnschedulePendingPlanChangesResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public PostSubscriptionsSubscriptionIdUnschedulePendingPlanChangesResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public PostSubscriptionsSubscriptionIdUnschedulePendingPlanChangesResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public Orb.Orb.models.shared.Subscription subscription;
    public PostSubscriptionsSubscriptionIdUnschedulePendingPlanChangesResponse withSubscription(Orb.Orb.models.shared.Subscription subscription) {
        this.subscription = subscription;
        return this;
    }
    
}
