/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PutCustomersCustomerIdRequestBody - The external payments or invoicing solution connected to this customer.
 */
public class PutCustomersCustomerIdRequestBody {
    /**
     * The customer's billing address; all fields in the address are optional. This address appears on customer invoices.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("billing_address")
    public PutCustomersCustomerIdRequestBodyBillingAddress billingAddress;

    public PutCustomersCustomerIdRequestBody withBillingAddress(PutCustomersCustomerIdRequestBodyBillingAddress billingAddress) {
        this.billingAddress = billingAddress;
        return this;
    }
    
    /**
     * A valid customer email, to be used for invoicing and notifications.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("email")
    public String email;

    public PutCustomersCustomerIdRequestBody withEmail(String email) {
        this.email = email;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("name")
    public String name;

    public PutCustomersCustomerIdRequestBody withName(String name) {
        this.name = name;
        return this;
    }
    
    /**
     * This is used for creating charges or invoices in an external system via Orb. When not in test mode:
     * - the connection must first be configured in the Orb webapp. 
     * - if the provider is an invoicing provider (`stripe_invoice`, `quickbooks`, `bill.com`), any product mappings must first be configured with the Orb team.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_provider")
    public PutCustomersCustomerIdRequestBodyPaymentProviderEnum paymentProvider;

    public PutCustomersCustomerIdRequestBody withPaymentProvider(PutCustomersCustomerIdRequestBodyPaymentProviderEnum paymentProvider) {
        this.paymentProvider = paymentProvider;
        return this;
    }
    
    /**
     * The ID of this customer in an external payments solution, such as Stripe. This is used for creating charges or invoices in the external system via Orb.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_provider_id")
    public String paymentProviderId;

    public PutCustomersCustomerIdRequestBody withPaymentProviderId(String paymentProviderId) {
        this.paymentProviderId = paymentProviderId;
        return this;
    }
    
    /**
     * The customer's shipping address; all fields in the address are optional. Note that downstream tax calculations are based on the shipping address.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("shipping_address")
    public PutCustomersCustomerIdRequestBodyShippingAddress shippingAddress;

    public PutCustomersCustomerIdRequestBody withShippingAddress(PutCustomersCustomerIdRequestBodyShippingAddress shippingAddress) {
        this.shippingAddress = shippingAddress;
        return this;
    }
    
    public PutCustomersCustomerIdRequestBody(){}
}
