/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;

public class PutCustomersCustomerIdRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public PutCustomersCustomerIdRequestBody requestBody;
    public PutCustomersCustomerIdRequest withRequestBody(PutCustomersCustomerIdRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Orb customer ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=customer_id")
    public String customerId;
    public PutCustomersCustomerIdRequest withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }
    
}
