/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class PutDeprecateEventsEventIdResponse {
    
    public String contentType;
    public PutDeprecateEventsEventIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public PutDeprecateEventsEventIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public PutDeprecateEventsEventIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public PutDeprecateEventsEventId200ApplicationJSON putDeprecateEventsEventId200ApplicationJSONObject;
    public PutDeprecateEventsEventIdResponse withPutDeprecateEventsEventId200ApplicationJSONObject(PutDeprecateEventsEventId200ApplicationJSON putDeprecateEventsEventId200ApplicationJSONObject) {
        this.putDeprecateEventsEventId200ApplicationJSONObject = putDeprecateEventsEventId200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public PutDeprecateEventsEventId400ApplicationJSON putDeprecateEventsEventId400ApplicationJSONObject;
    public PutDeprecateEventsEventIdResponse withPutDeprecateEventsEventId400ApplicationJSONObject(PutDeprecateEventsEventId400ApplicationJSON putDeprecateEventsEventId400ApplicationJSONObject) {
        this.putDeprecateEventsEventId400ApplicationJSONObject = putDeprecateEventsEventId400ApplicationJSONObject;
        return this;
    }
    
    public PutDeprecateEventsEventIdResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
