/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import java.net.http.HttpResponse;

public class PutEventsEventIdResponse {
    
    public String contentType;
    public PutEventsEventIdResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;
    public PutEventsEventIdResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;
    public PutEventsEventIdResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public PutEventsEventId200ApplicationJSON putEventsEventId200ApplicationJSONObject;
    public PutEventsEventIdResponse withPutEventsEventId200ApplicationJSONObject(PutEventsEventId200ApplicationJSON putEventsEventId200ApplicationJSONObject) {
        this.putEventsEventId200ApplicationJSONObject = putEventsEventId200ApplicationJSONObject;
        return this;
    }
    
    /**
     * Bad Request
     */
    
    public PutEventsEventId400ApplicationJSON putEventsEventId400ApplicationJSONObject;
    public PutEventsEventIdResponse withPutEventsEventId400ApplicationJSONObject(PutEventsEventId400ApplicationJSON putEventsEventId400ApplicationJSONObject) {
        this.putEventsEventId400ApplicationJSONObject = putEventsEventId400ApplicationJSONObject;
        return this;
    }
    
}
