/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class RevertBackfillRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=backfill_id")
    public String backfillId;

    public RevertBackfillRequest withBackfillId(String backfillId) {
        this.backfillId = backfillId;
        return this;
    }
    
    public RevertBackfillRequest(@JsonProperty("backfill_id") String backfillId) {
        this.backfillId = backfillId;
  }
}
