/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SchedulePlanChangeRequestBodyPriceOverrides1ModelType {
    TIERED("tiered");

    @JsonValue
    public final String value;

    private SchedulePlanChangeRequestBodyPriceOverrides1ModelType(String value) {
        this.value = value;
    }
}
