/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SchedulePlanChangeRequestBodyPriceOverrides5 - BPS price override
 */
public class SchedulePlanChangeRequestBodyPriceOverrides5 {
    @JsonProperty("bps_config")
    public SchedulePlanChangeRequestBodyPriceOverrides5BpsConfig bpsConfig;

    public SchedulePlanChangeRequestBodyPriceOverrides5 withBpsConfig(SchedulePlanChangeRequestBodyPriceOverrides5BpsConfig bpsConfig) {
        this.bpsConfig = bpsConfig;
        return this;
    }
    
    @JsonProperty("id")
    public String id;

    public SchedulePlanChangeRequestBodyPriceOverrides5 withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The subscription's override minimum amount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimum_amount")
    public String minimumAmount;

    public SchedulePlanChangeRequestBodyPriceOverrides5 withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("model_type")
    public SchedulePlanChangeRequestBodyPriceOverrides5ModelType modelType;

    public SchedulePlanChangeRequestBodyPriceOverrides5 withModelType(SchedulePlanChangeRequestBodyPriceOverrides5ModelType modelType) {
        this.modelType = modelType;
        return this;
    }
    
    public SchedulePlanChangeRequestBodyPriceOverrides5(@JsonProperty("bps_config") SchedulePlanChangeRequestBodyPriceOverrides5BpsConfig bpsConfig, @JsonProperty("id") String id, @JsonProperty("model_type") SchedulePlanChangeRequestBodyPriceOverrides5ModelType modelType) {
        this.bpsConfig = bpsConfig;
        this.id = id;
        this.modelType = modelType;
  }
}
