/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SchedulePlanChangeRequestBodyPriceOverrides5BpsConfig {
    @JsonProperty("bps")
    public Double bps;

    public SchedulePlanChangeRequestBodyPriceOverrides5BpsConfig withBps(Double bps) {
        this.bps = bps;
        return this;
    }
    
    @JsonProperty("per_unit_maximum")
    public String perUnitMaximum;

    public SchedulePlanChangeRequestBodyPriceOverrides5BpsConfig withPerUnitMaximum(String perUnitMaximum) {
        this.perUnitMaximum = perUnitMaximum;
        return this;
    }
    
    public SchedulePlanChangeRequestBodyPriceOverrides5BpsConfig(@JsonProperty("bps") Double bps, @JsonProperty("per_unit_maximum") String perUnitMaximum) {
        this.bps = bps;
        this.perUnitMaximum = perUnitMaximum;
  }
}
