/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SchedulePlanChangeRequestBodyPriceOverrides2 - Unit price override
 */
public class SchedulePlanChangeRequestBodyPriceOverrides2 {
    @JsonProperty("id")
    public String id;

    public SchedulePlanChangeRequestBodyPriceOverrides2 withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The subscription's override minimum amount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimum_amount")
    public String minimumAmount;

    public SchedulePlanChangeRequestBodyPriceOverrides2 withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("model_type")
    public SchedulePlanChangeRequestBodyPriceOverrides2ModelType modelType;

    public SchedulePlanChangeRequestBodyPriceOverrides2 withModelType(SchedulePlanChangeRequestBodyPriceOverrides2ModelType modelType) {
        this.modelType = modelType;
        return this;
    }
    
    @JsonProperty("unit_config")
    public SchedulePlanChangeRequestBodyPriceOverrides2UnitConfig unitConfig;

    public SchedulePlanChangeRequestBodyPriceOverrides2 withUnitConfig(SchedulePlanChangeRequestBodyPriceOverrides2UnitConfig unitConfig) {
        this.unitConfig = unitConfig;
        return this;
    }
    
    public SchedulePlanChangeRequestBodyPriceOverrides2(@JsonProperty("id") String id, @JsonProperty("model_type") SchedulePlanChangeRequestBodyPriceOverrides2ModelType modelType, @JsonProperty("unit_config") SchedulePlanChangeRequestBodyPriceOverrides2UnitConfig unitConfig) {
        this.id = id;
        this.modelType = modelType;
        this.unitConfig = unitConfig;
  }
}
