/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SchedulePlanChangeRequestBodyPriceOverrides4 - Package price override
 */
public class SchedulePlanChangeRequestBodyPriceOverrides4 {
    @JsonProperty("id")
    public String id;

    public SchedulePlanChangeRequestBodyPriceOverrides4 withId(String id) {
        this.id = id;
        return this;
    }
    
    /**
     * The subscription's override minimum amount for this price.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("minimum_amount")
    public String minimumAmount;

    public SchedulePlanChangeRequestBodyPriceOverrides4 withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("model_type")
    public SchedulePlanChangeRequestBodyPriceOverrides4ModelType modelType;

    public SchedulePlanChangeRequestBodyPriceOverrides4 withModelType(SchedulePlanChangeRequestBodyPriceOverrides4ModelType modelType) {
        this.modelType = modelType;
        return this;
    }
    
    @JsonProperty("package_config")
    public SchedulePlanChangeRequestBodyPriceOverrides4PackageConfig packageConfig;

    public SchedulePlanChangeRequestBodyPriceOverrides4 withPackageConfig(SchedulePlanChangeRequestBodyPriceOverrides4PackageConfig packageConfig) {
        this.packageConfig = packageConfig;
        return this;
    }
    
    public SchedulePlanChangeRequestBodyPriceOverrides4(@JsonProperty("id") String id, @JsonProperty("model_type") SchedulePlanChangeRequestBodyPriceOverrides4ModelType modelType, @JsonProperty("package_config") SchedulePlanChangeRequestBodyPriceOverrides4PackageConfig packageConfig) {
        this.id = id;
        this.modelType = modelType;
        this.packageConfig = packageConfig;
  }
}
