/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SchedulePlanChangeRequestBodyPriceOverrides3BulkConfig {
    @JsonProperty("tiers")
    public SchedulePlanChangeRequestBodyPriceOverrides3BulkConfigTiers[] tiers;

    public SchedulePlanChangeRequestBodyPriceOverrides3BulkConfig withTiers(SchedulePlanChangeRequestBodyPriceOverrides3BulkConfigTiers[] tiers) {
        this.tiers = tiers;
        return this;
    }
    
    public SchedulePlanChangeRequestBodyPriceOverrides3BulkConfig(@JsonProperty("tiers") SchedulePlanChangeRequestBodyPriceOverrides3BulkConfigTiers[] tiers) {
        this.tiers = tiers;
  }
}
