/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfigTiers {
    @JsonProperty("bps")
    public Double bps;

    public SchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfigTiers withBps(Double bps) {
        this.bps = bps;
        return this;
    }
    
    @JsonProperty("maximum_amount")
    public String maximumAmount;

    public SchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfigTiers withMaximumAmount(String maximumAmount) {
        this.maximumAmount = maximumAmount;
        return this;
    }
    
    @JsonProperty("minimum_amount")
    public String minimumAmount;

    public SchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfigTiers withMinimumAmount(String minimumAmount) {
        this.minimumAmount = minimumAmount;
        return this;
    }
    
    @JsonProperty("per_unit_maximum")
    public String perUnitMaximum;

    public SchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfigTiers withPerUnitMaximum(String perUnitMaximum) {
        this.perUnitMaximum = perUnitMaximum;
        return this;
    }
    
    public SchedulePlanChangeRequestBodyPriceOverrides7TieredBpsConfigTiers(@JsonProperty("bps") Double bps, @JsonProperty("maximum_amount") String maximumAmount, @JsonProperty("minimum_amount") String minimumAmount, @JsonProperty("per_unit_maximum") String perUnitMaximum) {
        this.bps = bps;
        this.maximumAmount = maximumAmount;
        this.minimumAmount = minimumAmount;
        this.perUnitMaximum = perUnitMaximum;
  }
}
