/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;

public class SearchEventsResponse {
    
    public String contentType;

    public SearchEventsResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public Integer statusCode;

    public SearchEventsResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public SearchEventsResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public SearchEvents200ApplicationJSON searchEvents200ApplicationJSONObject;

    public SearchEventsResponse withSearchEvents200ApplicationJSONObject(SearchEvents200ApplicationJSON searchEvents200ApplicationJSONObject) {
        this.searchEvents200ApplicationJSONObject = searchEvents200ApplicationJSONObject;
        return this;
    }
    
    public SearchEventsResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
