/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.operations;

import Orb.Orb.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateCustomerRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public UpdateCustomerRequestBody requestBody;

    public UpdateCustomerRequest withRequestBody(UpdateCustomerRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }
    
    /**
     * Orb customer ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=customer_id")
    public String customerId;

    public UpdateCustomerRequest withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }
    
    public UpdateCustomerRequest(@JsonProperty("customer_id") String customerId) {
        this.customerId = customerId;
  }
}
