/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * BackfillStatus - The status of the backfill.
 */
public enum BackfillStatus {
    PENDING("pending"),
    REFLECTED("reflected"),
    PENDING_REVERT("pending_revert"),
    REVERTED("reverted");

    @JsonValue
    public final String value;

    private BackfillStatus(String value) {
        this.value = value;
    }
}
