/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreditNoteReason - A reason for this credit note, which can be one of "Duplicate", "Fraudulent", "Order change", "Product unsatisfactory"
 */
public enum CreditNoteReason {
    DUPLICATE("Duplicate"),
    FRAUDULENT("Fraudulent"),
    ORDER_CHANGE("Order change"),
    PRODUCT_UNSATISFACTORY("Product unsatisfactory");

    @JsonValue
    public final String value;

    private CreditNoteReason(String value) {
        this.value = value;
    }
}
