/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreditLedgerEntryEntryStatusEnum - Committed entries are older than the ingestion grace period, and cannot change. Pending entries are newer than the grace period and are subject to updates
 */
public enum CreditLedgerEntryEntryStatusEnum {
    COMMITTED("committed"),
    PENDING("pending");

    @JsonValue
    public final String value;

    private CreditLedgerEntryEntryStatusEnum(String value) {
        this.value = value;
    }
}
