/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum CreditLedgerEntryEntryTypeEnum {
    INCREMENT("increment"),
    DECREMENT("decrement"),
    EXPIRATION_CHANGE("expiration_change"),
    CREDIT_BLOCK_EXPIRY("credit_block_expiry");

    @JsonValue
    public final String value;

    private CreditLedgerEntryEntryTypeEnum(String value) {
        this.value = value;
    }
}
