/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;



/**
 * CreditLedgerEntryMetadata - User-specified metadata dictionary that's specified when adding a ledger entry. This contains key/value pairs if metadata is specified, but otherwise is an empty dictionary.
 */
public class CreditLedgerEntryMetadata {
    public CreditLedgerEntryMetadata(){}
}
