/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CreditNoteCustomer - The Customer who is receiving this credit note.
 */
public class CreditNoteCustomer {
    @JsonProperty("external_customer_id")
    public String externalCustomerId;

    public CreditNoteCustomer withExternalCustomerId(String externalCustomerId) {
        this.externalCustomerId = externalCustomerId;
        return this;
    }
    
    @JsonProperty("id")
    public String id;

    public CreditNoteCustomer withId(String id) {
        this.id = id;
        return this;
    }
    
    public CreditNoteCustomer(@JsonProperty("external_customer_id") String externalCustomerId, @JsonProperty("id") String id) {
        this.externalCustomerId = externalCustomerId;
        this.id = id;
  }
}
