/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CustomerBalanceTransactionAction - Describes the reason that this transaction took place.
 */
public enum CustomerBalanceTransactionAction {
    APPLIED_TO_INVOICE("applied_to_invoice"),
    PRORATED_REFUND("prorated_refund"),
    MANUAL_ADJUSTMENT("manual_adjustment");

    @JsonValue
    public final String value;

    private CustomerBalanceTransactionAction(String value) {
        this.value = value;
    }
}
