/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CustomerPaymentProvider - The external payments or invoicing solution connected to this customer.
 */
public enum CustomerPaymentProvider {
    STRIPE("stripe"),
    QUICKBOOKS("quickbooks"),
    BILL_COM("bill.com"),
    STRIPE_CHARGE("stripe_charge"),
    STRIPE_INVOICE("stripe_invoice"),
    LESS_THAN_NIL_GREATER_THAN("<nil>");

    @JsonValue
    public final String value;

    private CustomerPaymentProvider(String value) {
        this.value = value;
    }
}
