/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CustomerBalanceTransactionInvoice - The Invoice associated with this transaction
 */
public class CustomerBalanceTransactionInvoice {
    /**
     * The Invoice id
     */
    @JsonProperty("id")
    public String id;

    public CustomerBalanceTransactionInvoice withId(String id) {
        this.id = id;
        return this;
    }
    
    public CustomerBalanceTransactionInvoice(@JsonProperty("id") String id) {
        this.id = id;
  }
}
