/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * InvoiceStatus - The status of this invoice as known to Orb. Invoices that have been issued for past billing periods are marked `"issued"`. Invoices will be marked `"paid"` upon confirmation of successful automatic payment collection by Orb. Invoices synced to an external billing provider (such as Bill.com, QuickBooks, or Stripe Invoicing) will be marked as `"synced"`.
 */
public enum InvoiceStatus {
    ISSUED("issued"),
    PAID("paid"),
    SYNCED("synced");

    @JsonValue
    public final String value;

    private InvoiceStatus(String value) {
        this.value = value;
    }
}
