/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * PriceBulkConfig - Provided when model_type is `bulk`
 */
public class PriceBulkConfig {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tiers")
    public PriceBulkConfigTiers[] tiers;

    public PriceBulkConfig withTiers(PriceBulkConfigTiers[] tiers) {
        this.tiers = tiers;
        return this;
    }
    
    public PriceBulkConfig(){}
}
