/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum SubscriptionStatus {
    ACTIVE("active"),
    ENDED("ended"),
    UPCOMING("upcoming");

    @JsonValue
    public final String value;

    private SubscriptionStatus(String value) {
        this.value = value;
    }
}
