/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class UpcomingInvoiceLineItemsSubLineItems {
    /**
     * The total amount for this sub line item.
     */
    @JsonProperty("amount")
    public String amount;
    public UpcomingInvoiceLineItemsSubLineItems withAmount(String amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * Only available if `type` is `matrix`. Contains the values of the matrix that this `sub_line_item` represents.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("matrix_config")
    public UpcomingInvoiceLineItemsSubLineItemsMatrixConfig matrixConfig;
    public UpcomingInvoiceLineItemsSubLineItems withMatrixConfig(UpcomingInvoiceLineItemsSubLineItemsMatrixConfig matrixConfig) {
        this.matrixConfig = matrixConfig;
        return this;
    }
    
    @JsonProperty("name")
    public String name;
    public UpcomingInvoiceLineItemsSubLineItems withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonProperty("quantity")
    public Double quantity;
    public UpcomingInvoiceLineItemsSubLineItems withQuantity(Double quantity) {
        this.quantity = quantity;
        return this;
    }
    
    /**
     * Only available if `type` is `tier`. Contains the range of units in this tier and the unit amount.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tier_config")
    public UpcomingInvoiceLineItemsSubLineItemsTierConfig tierConfig;
    public UpcomingInvoiceLineItemsSubLineItems withTierConfig(UpcomingInvoiceLineItemsSubLineItemsTierConfig tierConfig) {
        this.tierConfig = tierConfig;
        return this;
    }
    
    /**
     * An identifier for a sub line item that is specific to a pricing model.
     */
    @JsonProperty("type")
    public UpcomingInvoiceLineItemsSubLineItemsTypeEnum type;
    public UpcomingInvoiceLineItemsSubLineItems withType(UpcomingInvoiceLineItemsSubLineItemsTypeEnum type) {
        this.type = type;
        return this;
    }
    

    public UpcomingInvoiceLineItemsSubLineItems(@JsonProperty("amount") String amount, @JsonProperty("name") String name, @JsonProperty("quantity") Double quantity, @JsonProperty("type") UpcomingInvoiceLineItemsSubLineItemsTypeEnum type) {
    this.amount = amount;
this.name = name;
this.quantity = quantity;
this.type = type;
  }
}
