/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import Orb.Orb.utils.DateTimeDeserializer;
import Orb.Orb.utils.DateTimeSerializer;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.OffsetDateTime;

public class UpcomingInvoiceLineItems {
    /**
     * The final amount after any discounts or minimums.
     */
    @JsonProperty("amount")
    public String amount;
    public UpcomingInvoiceLineItems withAmount(String amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * The end date of the range of time applied for this line item's price.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("end_date")
    public OffsetDateTime endDate;
    public UpcomingInvoiceLineItems withEndDate(OffsetDateTime endDate) {
        this.endDate = endDate;
        return this;
    }
    
    /**
     * For configured prices that are split by a grouping key, this will be populated with the key and a value. The `amount` and `subtotal` will be the values for this particular grouping.
     */
    @JsonProperty("grouping")
    public UpcomingInvoiceLineItemsGrouping grouping;
    public UpcomingInvoiceLineItems withGrouping(UpcomingInvoiceLineItemsGrouping grouping) {
        this.grouping = grouping;
        return this;
    }
    
    /**
     * The name of the price associated with this line item.
     */
    @JsonProperty("name")
    public String name;
    public UpcomingInvoiceLineItems withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonProperty("quantity")
    public Double quantity;
    public UpcomingInvoiceLineItems withQuantity(Double quantity) {
        this.quantity = quantity;
        return this;
    }
    
    /**
     * The start date of the range of time applied for this line item's price.
     */
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("start_date")
    public OffsetDateTime startDate;
    public UpcomingInvoiceLineItems withStartDate(OffsetDateTime startDate) {
        this.startDate = startDate;
        return this;
    }
    
    /**
     * For complex pricing structures, the line item can be broken down further in `sub_line_items`.
     */
    @JsonProperty("sub_line_items")
    public UpcomingInvoiceLineItemsSubLineItems[] subLineItems;
    public UpcomingInvoiceLineItems withSubLineItems(UpcomingInvoiceLineItemsSubLineItems[] subLineItems) {
        this.subLineItems = subLineItems;
        return this;
    }
    
    /**
     * The line amount before any line item-specific discounts or minimums.
     */
    @JsonProperty("subtotal")
    public String subtotal;
    public UpcomingInvoiceLineItems withSubtotal(String subtotal) {
        this.subtotal = subtotal;
        return this;
    }
    

    public UpcomingInvoiceLineItems(@JsonProperty("amount") String amount, @JsonProperty("end_date") OffsetDateTime endDate, @JsonProperty("grouping") UpcomingInvoiceLineItemsGrouping grouping, @JsonProperty("name") String name, @JsonProperty("quantity") Double quantity, @JsonProperty("start_date") OffsetDateTime startDate, @JsonProperty("sub_line_items") UpcomingInvoiceLineItemsSubLineItems[] subLineItems, @JsonProperty("subtotal") String subtotal) {
    this.amount = amount;
this.endDate = endDate;
this.grouping = grouping;
this.name = name;
this.quantity = quantity;
this.startDate = startDate;
this.subLineItems = subLineItems;
this.subtotal = subtotal;
  }
}
