/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Orb.Orb.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UpcomingInvoiceSubscription - The associated subscription for this invoice.
 */
public class UpcomingInvoiceSubscription {
    @JsonProperty("id")
    public String id;
    public UpcomingInvoiceSubscription withId(String id) {
        this.id = id;
        return this;
    }
    
    public UpcomingInvoiceSubscription(@JsonProperty("id") String id) {
        this.id = id;
  }
}
